spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/financiera
    username: postgres
    password: bdversion18
  flyway:
    locations: classpath:db/migration,classpath:db/dev-seed
    validate-on-migrate: false
  jpa:
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    enabled: true

security:
  jwt:
    secret: local-dev-secret-64chars-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!
  cors:
    allowed-origins: http://localhost:4200

logging:
  level:
    root: INFO
    co.pluto: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
